package constants

const ERROR_INCORRENT_BODY = "INCORRENT_BODY"
const ERROR_MONGO_ERROR = "MONGO_ERROR"

var ERROR_FETCH_JWK string = "FETCH_JWK_ERROR"
var ERROR_CONVERT_JWT_TO_BYTES string = "ERROR_CONVERT_JWT_TO_BYTES"
var ERROR_PARSING_JWK string = "ERROR_PARSING_JWK"
var ERROR_TOKEN_SIGNATURE_INVALID string = "ERROR_TOKEN_SIGNATURE_INVALID"
var ERROR_GETTING_EMAIL string = "ERROR_GETTING_EMAIL"
var ERROR_INVALID_TOKEN string = "ERROR_INVALID_TOKEN"
var ERROR_FAILED_FETCH_FROM_DB string = "ERROR_FAILED_FETCH_FROM_DB"

var ERROR_NOT_A_STUDENT string = "ERROR_NOT_A_STUDENT"

var ERROR_ROLE_CHECK_FAILED string = "ERROR_ROLE_CHECKED_FAILED"
